SELECT * FROM PLAN_TABLE;

EXPLAIN PLAN FOR
SELECT
    B.DNAME,
    A.JOB,
    SUM(A.SAL) SAL,
    COUNT(A.EMPNO) EMP_COUNT
FROM EMP A, DEPT B
WHERE A.DEPTNO = B.DEPTNO
GROUP BY CUBE(B.DNAME, A.JOB)
ORDER BY DNAME;